Fix sorting error on None values
```python
  File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/hooks/relations/public-address/requires.py", line 43, in get_addresses_ports
    return [{'public-address': pa, 'port': p} for pa, p in sorted(hosts)]
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```